"""Stable, platform-independent Agent Black Box domain contracts."""

from blackbox.domain.policy import (
    POLICY_PLUGINS, BuiltinPolicy, PolicyPlugin, PolicyResult, PolicySet,
    evaluate_policy_plugins,
)
from blackbox.domain.result import CaseResult, Comparison, RunScore
from blackbox.domain.schema import CURRENT_SCHEMA_VERSION
from blackbox.domain.suite import (
    Assertion, Case, Dataset, EvaluationCase, FixtureRef, SamplingConfig,
)
from blackbox.domain.trace import (
    AgentHandoff,
    AgentHandoffEvent,
    ArtifactRef,
    Conversation,
    Cost,
    CustomEvent,
    ErrorEvent,
    ErrorInfo,
    EvaluatorResultEvent,
    Event,
    HumanReviewEvent,
    Message,
    ModelRequestEvent,
    ModelResponseEvent,
    PolicyDecisionEvent,
    RetrievalEvent,
    Span,
    SpanLink,
    Step,
    ToolRequestEvent,
    ToolResponseEvent,
    Trace,
    Turn,
    Usage,
    Violation,
    Citation,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "Case",
    "EvaluationCase",
    "Assertion",
    "Dataset",
    "FixtureRef",
    "SamplingConfig",
    "CaseResult",
    "AgentHandoff",
    "AgentHandoffEvent",
    "ArtifactRef",
    "Citation",
    "Comparison",
    "Conversation",
    "Cost",
    "CustomEvent",
    "ErrorEvent",
    "ErrorInfo",
    "EvaluatorResultEvent",
    "Event",
    "HumanReviewEvent",
    "Message",
    "ModelRequestEvent",
    "ModelResponseEvent",
    "PolicySet",
    "PolicyPlugin",
    "PolicyResult",
    "BuiltinPolicy",
    "POLICY_PLUGINS",
    "evaluate_policy_plugins",
    "PolicyDecisionEvent",
    "RetrievalEvent",
    "RunScore",
    "Span",
    "SpanLink",
    "Step",
    "ToolRequestEvent",
    "ToolResponseEvent",
    "Trace",
    "Turn",
    "Usage",
    "Violation",
]
