"""Compatibility exports for the schema-v2 trace API.

New code should import from :mod:`blackbox.domain.trace`.
"""

import warnings

warnings.warn(
    "blackbox.trace is a compatibility module; import trace contracts from "
    "blackbox.domain.trace",
    DeprecationWarning,
    stacklevel=2,
)

from blackbox.domain.trace import (
    AgentHandoff,
    AgentHandoffEvent,
    ArtifactRef,
    Conversation,
    Cost,
    CustomEvent,
    DEFAULT_PAYLOAD_LIMIT,
    ErrorEvent,
    ErrorInfo,
    EvaluatorResultEvent,
    Event,
    HumanReviewEvent,
    JSONLWriter,
    Message,
    ModelRequestEvent,
    ModelResponseEvent,
    PayloadTooLargeError,
    PolicyDecisionEvent,
    RetrievalEvent,
    STEP_KINDS,
    Span,
    SpanLink,
    Citation,
    Step,
    ToolRequestEvent,
    ToolResponseEvent,
    Trace,
    TraceCorruptionError,
    TraceValidationError,
    Turn,
    Usage,
    Violation,
    canonical_json,
    content_digest,
    event_from_dict,
    iter_traces,
    load_traces,
    new_ulid,
    now,
    save_traces,
)

__all__ = [
    "STEP_KINDS",
    "AgentHandoff",
    "AgentHandoffEvent",
    "ArtifactRef",
    "Citation",
    "Conversation",
    "Cost",
    "CustomEvent",
    "DEFAULT_PAYLOAD_LIMIT",
    "ErrorEvent",
    "ErrorInfo",
    "EvaluatorResultEvent",
    "Event",
    "HumanReviewEvent",
    "JSONLWriter",
    "Message",
    "ModelRequestEvent",
    "ModelResponseEvent",
    "PayloadTooLargeError",
    "PolicyDecisionEvent",
    "RetrievalEvent",
    "Span",
    "SpanLink",
    "Step",
    "ToolRequestEvent",
    "ToolResponseEvent",
    "Trace",
    "TraceCorruptionError",
    "TraceValidationError",
    "Turn",
    "Usage",
    "Violation",
    "canonical_json",
    "content_digest",
    "event_from_dict",
    "iter_traces",
    "load_traces",
    "new_ulid",
    "now",
    "save_traces",
]
